################################################################################
#                              Terminal Theme                                  #
################################################################################

name = "Terminal"
license = "MIT"
licenselink = "https://github.com/AravindVasudev/Terminal/blob/main/LICENSE"
description = ""
homepage = "https://aravindvasu.dev/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Aravind Vasudevan"
  homepage = "https://aravindvasu.dev/"